name: Statues
main: haveric.statues.Statues
version: 0.3
depend: [Vault]
author: haveric
description: >
             Create statues
commands:
    statues:
    	aliases: [statue]
        description: Create statues
        usage: